export const CHECKLIST_DATA = [
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.1', item: '검사활동 수행의 공평성 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.2', item: '검사업무에 부정적인 영향을 미치는 압력을 배제할 수 있는 절차 및 실행여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.3', item: '지속적으로 공평성에 대한 위험을 식별하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.4', item: '공평성에 대한 위험이 확인된 경우 제거하고 최소화하기 위한 방법의 입증 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.5', item: '공평성에 대한 최고 경영자의 진술 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.1 공평성 및 독립성', id: '4.1.6', item: '검사기관 유형별 최소요구사항 (독립성 정도) 충족 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.2 기밀유지', id: '4.2.1', item: '취득 또는 생성한 정보의 기밀유지 및 소유권 보호를 위한 법적 구속력 있는 진술 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.2 기밀유지', id: '4.2.2', item: '공개된 정보에 대한 고객 통지 여부', status: null, memo: '', evidence: '' },
  { section: '4. 일반 요구사항', sub: '4.2 기밀유지', id: '4.2.3', item: '다른 출처로부터 취득한 고객에 대한 정보에 대한 기밀유지 여부', status: null, memo: '', evidence: '' },
  
  { section: '5. 조직 구조 요구사항', sub: '5.1 행정적 요구사항', id: '5.1.1', item: '검사활동의 법적 책임을 위한 법적실체 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.1 행정적 요구사항', id: '5.1.2', item: '법적 조직의 일부가 검사 이외의 활동에 연관된 경우 조직 내에서 확인 가능한지 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.1 행정적 요구사항', id: '5.1.3', item: '검사기관의 검사업무 및 활동범위를 규정한 문서 구비여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.1 행정적 요구사항', id: '5.1.4', item: '검사기관의 책임사항을 보장하기 위한 적합한 대비책 보유 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.1 행정적 요구사항', id: '5.1.5', item: '모조직에 검사서비스를 제공하는 경우를 제외하고, 계약조건을 기술한 문서의 보유 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.1', item: '공평성을 보호하기 위해 검사 수행 부서의 독립적인 구성 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.2', item: '검사활동 수행 능력 유지를 위한 조직화 및 관리여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.3', item: '검사기관의 전체 조직도내에 검사를 수행하는 조직이 식별되고, 주요 직원의 책임 및 보고 체계를 규정하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.4', item: '검사업무 외의 활동과 검사활동 사이의 관계 규정 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.5', item: '기술책임자 존재여부 및 적합한 자격 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.6', item: '기술부책임자의 임명 여부', status: null, memo: '', evidence: '' },
  { section: '5. 조직 구조 요구사항', sub: '5.2 조직 및 경영', id: '5.2.7', item: '검사실무자를 포함한 주요 직원, 경영, 검사수행도, 검사기록 또는 검사결과에 영향을 미칠 수 있는 기타 직원들의 직무기술서 보유 여부', status: null, memo: '', evidence: '' },
  
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.1', item: '검사활동에 연관된 모든 인원에 대한 자격 조건의 규정 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.2', item: '업무의 유형 범위 및 양에 부합한 충분한 수의 인원 확보 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.3', item: '검사실무자의 자격, 교육, 경험, 지식확보여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.4', item: '각 직원에게 명확한 임무, 책임 및 권한을 규정하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.5', item: '검사활동에 연관된 검사원 및 기타 인원과 관련하여 문서화된 절차 보유여부 (선정, 훈련, 공식적인 자격부여, 모니터링)', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.6', item: '경험있는 검사원 지도하의 작업기간, 지속적인 교육훈련 등을 고려한 문서화된 훈련절차 보유여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.7', item: '검사실무자 및 기타 직원의 훈련은 능력, 자격 및 경험 그리고 모니터링 결과에 따라 설정하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.8', item: '모니터링 절차 보유 및 이행여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.9', item: '검사실무자의 현장관찰 이행 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.10', item: '검사활동에서 직원에 대한 기록여부 (모니터링, 교육, 훈련, 지식, 경험 및 권한)', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.11', item: '검사결과에 영향을 미치는 방식으로 보수를 지급하지 않는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.12', item: '모든 직원(내·외부)의 공평한 방식으로 행동하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.1 인원', id: '6.1.13', item: '모든 검사자(내·외부)의 비밀 유지 방침의 이해 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.1', item: '인정(신청)범위에 해당하는 적합한 시설 및 장비를 갖추고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.2', item: '검사시설 및 장비의 접근 및 사용에 대한 규정 보유여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.3', item: '보유시설 및 장비의 지속적인 적합성 유지여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.4', item: '검사 결과에 중대한 영향이 있는 모든 장비를 규정하고, 적절하게 식별하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.5', item: '모든 장비는 문서화된 절차 및 지침을 이용해 유지관리 되는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.6', item: '검사 결과에 중대한 영향이 있는 측정장비는 사용이전에 교정프로그램에 따라 교정하는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.7', item: '교정프로그램에 따라 교정을 실시하고 측정소급성 확보가 어려운 경우 충분한 증거를 유지하는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.8', item: '검사기관이 보유한 교정용 표준기의 사용 목적 명확화 및 측정소급성 확보 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.9', item: '재교정 주기 이내라도 필요한 경우 장비에 대한 자체점검(중간점검) 실시 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.10', item: '가능한 한 표준물질의 국내 또는 국제표준물질과의 측정소급성 유지여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.11', item: '구매 절차의 적절성 (공급자의 선정 및 승인, 도입 품목의 확인, 적절한 보관 시설)', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.12', item: '보관된 검사관련 물품을 적절한 주기로 평가하는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.13', item: '컴퓨터 및 자동화 장비 관리의 적절성 (소프트웨어의 적절성, 데이터의 완전성 및 보안)', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.14', item: '결함장비의 관리 적절성 여부 및 이전 검사에 대한 결함장비 영향조사', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.2 시설 및 장비', id: '6.2.15', item: '장비 및 소프트웨어 관련 식별, 교정 및 유지관리 기록 보유 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.3 위탁계약', id: '6.3.1', item: '계약된 검사의 직접 수행능력 및 위탁계약자의 자격 적합성 확인 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.3 위탁계약', id: '6.3.2', item: '위탁계약에 대한 고객통보 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.3 위탁계약', id: '6.3.3', item: '위탁계약자의 검사품목 적합성 결정에 대한 책임을 검사기관이 보장하는지 여부', status: null, memo: '', evidence: '' },
  { section: '6. 자원 요구사항', sub: '6.3 위탁계약', id: '6.3.4', item: '위탁계약기관의 등록 및 평가기준 충족에 대한 조사 기록 여부', status: null, memo: '', evidence: '' },

  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.1', item: '규정된 검사방법 및 절차이용 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.2', item: '다음 사항에 대한 문서화된 지침 사용 여부 (검사 계획, 샘플링, 데이터 처리 등)', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.3', item: '표준화되지 않은 검사방법의 문서화 및 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.4', item: '모든 지침, 표준 또는 문서화된 절차서, 체크리스트를 최신본으로 유지하고 직원이 이용 가능한지 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.5', item: '수행되는 업무의 전문성을 보장하는 계약 또는 작업지시 관리 시스템 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.6', item: '검사과정의 일부에서 다른 이해당사자가 제공한 정보의 무결성 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.7', item: '검사관련 관찰사항 및 관련 자료의 적절한 기록여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.8', item: '계산결과 및 데이터 이전 과정의 적절한 점검여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.1 검사방법 및 절차', id: '7.1.9', item: '안전한 방법으로 검사를 수행하기 위한 문서화된 지침 보유 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.2 검사품목 및 샘플의 취급', id: '7.2.1', item: '검사대상 품목 및 샘플 식별의 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.2 검사품목 및 샘플의 취급', id: '7.2.2', item: '검사 전 검사대상 품목에 대한 준비사항 확인 시스템의 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.2 검사품목 및 샘플의 취급', id: '7.2.3', item: '품목에 의문이 있거나 기술된 바와 다를 경우 의뢰자에게 통보 여부 및 기록 유무', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.2 검사품목 및 샘플의 취급', id: '7.2.4', item: '검사품목의 품질저하 및 손상을 방지하는 절차 및 시설 보유 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.3 검사기록', id: '7.3.1', item: '검사절차의 효과적인 수행을 입증하고 검사의 평가를 가능하게 하는 기록시스템 유지여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.3 검사기록', id: '7.3.2', item: '검사 성적서 또는 증명서는 검사를 수행한 검사실무자(들)이 추적 가능한지 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.4 검사성적서 및 검사증명서', id: '7.4.1', item: '재생성(정정)할 수 있도록 검사성적서 및/또는 검사증명서를 보관하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.4 검사성적서 및 검사증명서', id: '7.4.2', item: '검사성적서의 포함사항 및 기술 내용의 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.4 검사성적서 및 검사증명서', id: '7.4.3', item: '검사증명서가 발행되는 경우, 검사결과를 포함하는 검사성적서와 상호 추적 가능 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.4 검사성적서 및 검사증명서', id: '7.4.4', item: '검사성적서 또는 증명서 정보의 정확성 및 명확성 보고여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.4 검사성적서 및 검사증명서', id: '7.4.5', item: '발행 이후 검사성적서 및 증명서의 수정 또는 추가 기록 시 내용의 적절성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.5 불만 및 이의제기', id: '7.5.1', item: '불만 및 이의제기에 대한 문서화된 절차 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.5 불만 및 이의제기', id: '7.5.2', item: '불만 및 이의제기 사항 취급에 대한 프로세스의 설명이 관련 이해당사자에게 제공되고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.5 불만 및 이의제기', id: '7.5.3', item: '불만을 접수한 경우 관련성 확인 및 처리 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.5 불만 및 이의제기', id: '7.5.4', item: '불만 및 이의제기처리의 모든 단계에서 결정에 대한 책임 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.5 불만 및 이의제기', id: '7.5.5', item: '이의 제기에 대한 조사 및 결정의 비차별성', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.6 불만 및 이의제기 프로세스', id: '7.6.1', item: '다음의 요소 및 방법이 프로세스에 포함되는지 여부 (접수, 조사, 조치, 적절성)', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.6 불만 및 이의제기 프로세스', id: '7.6.2', item: '불만 및 이의제기 확인 시 정보 수집 및 확인 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.6 불만 및 이의제기 프로세스', id: '7.6.3', item: '불만 및 이의제기의 결과 및 진행사항 보고 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.6 불만 및 이의제기 프로세스', id: '7.6.4', item: '검사활동에 관여하지 않은 개인(들)에 의한 검토 및 승인 여부', status: null, memo: '', evidence: '' },
  { section: '7. 프로세스 요구사항', sub: '7.6 불만 및 이의제기 프로세스', id: '7.6.5', item: '불만 및 이의 제기자에게 프로세스 종료에 대한 공식적인 통보 여부', status: null, memo: '', evidence: '' },

  { section: '8. 경영시스템 요구사항', sub: '8.1 선택사항', id: '8.1', item: '선택사항 A 또는 선택사항 B에 따라 경영시스템을 확립하고 유지하고 있는지 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.2 경영시스템 문서화', id: '8.2.1', item: '검사기관의 품질방침 및 목표 설정 유무, 조직의 인식 및 유지', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.2 경영시스템 문서화', id: '8.2.2', item: '경영시스템의 개발 및 실행과 지속적 성과달성의 효과성에 대한 적절성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.2 경영시스템 문서화', id: '8.2.3', item: '경영시스템 프로세스 유지 책임과 권한을 가진 경영진 맴버 지정 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.2 경영시스템 문서화', id: '8.2.4', item: '경영시스템 문서화의 적절성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.2 경영시스템 문서화', id: '8.2.5', item: '모든 직원의 관련 문서 및 관련 정보 접근성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.3 문서관리', id: '8.3.1', item: '관련 문서(내·외부)를 관리하는 절차 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.3 문서관리', id: '8.3.2', item: '절차에 승인, 검토, 식별 확인 등의 관리사항 규정 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.4 기록의 관리', id: '8.4.1', item: '기록에 대한 식별, 보관, 보호, 정정, 보존년한 및 폐기 절차 보유 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.4 기록의 관리', id: '8.4.2', item: '기록 보존 절차 보유 여부 및 기밀유지 준수 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.5 경영검토', id: '8.5.1', item: '최고경영자에 의해 계획된 주기에 따라 평가하고 경영검토의 기록 유지 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.5 경영검토', id: '8.5.2', item: '경영검토 내용 구성의 적절성 (내부심사결과, 피드백, 시정조치 등)', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.5 경영검토', id: '8.5.3', item: '경영검토 자료에 시스템 개선 및 자원 요구에 관련된 결정 및 조치의 포함 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.6 내부심사', id: '8.6.1', item: '내부심사 절차 수립 및 계획의 적절성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.6 내부심사', id: '8.6.2', item: '정기적이고 체계적인 내부심사(12개월 마다) 이행 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.6 내부심사', id: '8.6.3', item: '자격을 갖춘 인원 수행 여부 및 심사결과의 문서화, 처리 방식의 적절성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.7 시정조치', id: '8.7.1', item: '부적합사항 식별 및 관리 절차의 문서화 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.7 시정조치', id: '8.7.2', item: '재발방지를 위한 부적합사항 원인 제거 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.7 시정조치', id: '8.7.3', item: '시정조치 절차의 문서화 및 이행, 취해진 시정조치의 적절성', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.8 예방조치', id: '8.8.1', item: '예방조치 절차 수립 및 문서화, 이행 여부', status: null, memo: '', evidence: '' },
  { section: '8. 경영시스템 요구사항', sub: '8.8 예방조치', id: '8.8.2', item: '취해진 예방조치의 적절성 (부적합 발생 예방, 원인 식별, 효과성 검토)', status: null, memo: '', evidence: '' },
];
